name: Run Python Script

on:
  workflow_dispatch:
    inputs:
        data:
          description: "JSON stringified of rowdata"
          required: true
          type: string  # Incoming data will be a JSON string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“ Create Data File
        run: |
          echo "${{ github.event.inputs.data }}" > data.json 

      - name: âš™ï¸ Exec program
        run: ./install.sh

      - name: ğŸ Run Python Script
        run: source venv/bin/activate && python3 src/app.py
