name: Run Python Script

on:
  workflow_dispatch:
    inputs:
        title:
          description: "Title of the video"
          required: true
          type: string
        link:
          description: "Link to the video"
          required: true
          type: string 

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸ Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ“ Create Data File
        run: |
          echo '{"title":"${{github.event.inputs.title }}","link":"${{github.event.inputs.link}}"}' > data.json 

      - name: âš™ï¸ Exec program
        run: ./install.sh

      - name: ğŸ Run Python Script
        run: source venv/bin/activate && python3 src/app.py || (cat debug.html && exit 1)
